# euphoric_tools/CMakeLists.txt
# =============================================
# Builds Euphoric utility tools
# =============================================

add_subdirectory(4k8)
add_subdirectory(Bin2Tap)
add_subdirectory(dsk)
add_subdirectory(old2mfm)
add_subdirectory(tap2dsk)
add_subdirectory(txt2bas)
